= nng_mqtt_options(5)
//
// Copyright 2020 Staysail Systems, Inc. <info@staysail.tech>
// Copyright 2018 Capitar IT Group BV <info@capitar.com>
// Copyright 2019 Devolutions <info@devolutions.net>
//
// This document is supplied under the terms of the MIT License, a
// copy of which should be located in the distribution where this
// file was obtained (LICENSE.txt).  A copy of the license may also be
// found online at https://opensource.org/licenses/MIT.
//

== NAME

nng_mqtt_options - socket, dialer, listener, and pipe options.

== SYNOPSIS

[source, c]
----
#include <nng/mqtt/mqtt_client.h>

#define NNG_OPT_MQTT_CONNMSG "mqtt-connect-msg"
#define NNG_OPT_MQTT_CONNECT_PROPERTY "mqtt-connack-property"
#define NNG_OPT_MQTT_CONNECT_REASON "mqtt-connack-reason"
#define NNG_OPT_MQTT_RECONNECT_BACKOFF_MAX "mqtt-reconnect-backoff-max"
#define NNG_OPT_MQTT_DISCONNECT_PROPERTY "mqtt-disconnect-property"
#define NNG_OPT_MQTT_DISCONNECT_REASON "mqtt-disconnect-reason"
#define NNG_OPT_MQTT_SQLITE "mqtt-sqlite-option"
----

== DESCRIPTION

This page documents the various standard options that can be set or retrieved on objects using MQTT.

The option names should always be used by their symbolic definitions.

In the following list of options, the name of the option is supplied, along with the data type of the underlying value.

Some options are only meaningful or supported in certain contexts, or may have other access restrictions. An attempt has been made to include details about such restrictions in the description of the option.

=== MQTT Options

[[NNG_OPT_MQTT_CONNMSG]]
((`NNG_OPT_MQTT_CONNMSG`))::
(nng_msg*)
This is a flag of connection message. See xref:nng_mqtt_client_open.3.adoc[`nng_dialer_set_ptr()`] for more details. 

[[NNG_OPT_MQTT_CONNECT_PROPERTY]]
((`NNG_OPT_MQTT_CONNECT_PROPERTY`))::
(property*)
This is a flag of mqtt connect property. See xref:nng_pipe_get.3.adoc[`nng_dialer_get_ptr()`] for more details.

[[NNG_OPT_MQTT_CONNECT_REASON]]
((`NNG_OPT_MQTT_CONNECT_REASON`))::
(int)
This is a flag of mqtt connect reason code. See xref:nng_pipe_get.3.adoc[`nng_dialer_get_int()`] for more details.

[[NNG_OPT_MQTT_RECONNECT_BACKOFF_MAX]]
((`NNG_OPT_MQTT_RECONNECT_BACKOFF_MAX`))::
(int)
Auto-reconnect back off option.
NanoSDK uses a dialer mechanism to manage MQTT connections, which hides the reconnection operation, so users do not need to program the reconnection process based on the disconnection callback. However, it does not provide an automatic back off option, which can cause the client to reconnect too frequently, potentially leading to a DDOS attack on the broker. In this version, a built-in automatic exponential back off algorithm has been added, and users only need to set a maximum back off time to activate it. The client will automatically generate a random number between 0 and 2 as the waiting time (timeout), and then wait for timeout*2 for each reconnection attempt until it reaches the maximum value. See xref:nng_dialer_setopt.3.adoc[`nng_dialer_setopt_ms()`] for more details.


[[NNG_OPT_MQTT_DISCONNECT_PROPERTY]]
((`NNG_OPT_MQTT_DISCONNECT_PROPERTY`))::
(property*)
This is a flag of mqtt disconnect property. See xref:nng_pipe_get.3.adoc[`nng_dialer_get_ptr()`] for more details.

[[NNG_OPT_MQTT_DISCONNECT_REASON]]
((`NNG_OPT_MQTT_DISCONNECT_REASON`))::
(int)
This is a flag of mqtt disconnect reason code. See xref:nng_pipe_get.3.adoc[`nng_dialer_get_int()`] for more details.

[[NNG_OPT_MQTT_SQLITE]]
((`NNG_OPT_MQTT_SQLITE`))::
(nng_mqtt_sqlite_option *)
Set sqlite option pointer to socket. See xref:nng_mqtt_client_open.3.adoc[`nng_dialer_set_ptr()`] for more details. 

== SEE ALSO

[.text-left]
xref:nng_mqtt_client_open.3.adoc[nng_dialer_set_ptr()]
xref:nng_dialer_getopt.3.adoc[nng_dialer_getopt(3)],
xref:nng_dialer_setopt.3.adoc[nng_dialer_setopt(3)],
xref:nng_getopt.3.adoc[nng_getopt(3)],
xref:nng_listener_getopt.3.adoc[nng_listener_getopt(3)],
xref:nng_listener_setopt.3.adoc[nng_listener_setopt(3)],
xref:nng_pipe_getopt.3.adoc[nng_pipe_getopt(3)],
xref:nng_setopt.3.adoc[nng_setopt(3)],
xref:nng_ipc_options.5.adoc[nng_ipc_options(5)],
xref:nng_tcp_options.5.adoc[nng_tcp_options(5)],
xref:nng_tls_options.5.adoc[nng_tls_options(5)],
xref:nng.7.adoc[nng(7)]
