name: windows
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: [windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: vcpkg build
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          pkgs: mbedtls
          triplet: x64-windows
          token: ${{ github.token }}
          github-binarycache: true

      - name: Configure
        # TLS on Windows is not good because vcpkg is *old* mbedTLS 2.28, and we don't pass some newer tests.
        # We should explore testing WolfSSL here instead.
        run: cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest -C Debug --output-on-failure
