name: windows
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: [windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: vcpkg build
        id: vcpkg
        uses: johnwason/vcpkg-action@v6
        with:
          pkgs: mbedtls
          triplet: x64-windows-release
          token: ${{ github.token }}
          github-binarycache: true

      - name: Configure
        run: cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }} -G Ninja -D NNG_ENABLE_TLS=ON -B build

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest -C Debug --output-on-failure
